version: '3.9'
services:
  app:
    build:
      context: .
      target: development
      args:
        - APP_PORT=${APP_PORT}
    volumes:
      - .:/usr/src/app
    container_name: express-todo-app
    restart: always
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=todo_app_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: